name: Localhost Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build the React App
        run: npm run build

      - name: Deploy to Localhost via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: kali
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "/home/kali/react-app"

      - name: Start Static Server (optional)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: kali
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/kali/react-app
            npx serve -s . -l 4000
